// AUTO-GENERATED by scripts/gen-epf-history.py — DO NOT EDIT BY HAND.
// Source: EPFO passbook PDFs (4 member IDs, FY2018-2026). Pension (EPS) excluded.
// Re-run the generator when new passbooks arrive.
//
// Reconciled: contributions ₹1,625,975 + interest ₹296,970 = ₹1,922,945.

export type EpfHistoryPoint = {
  /** ISO date (YYYY-MM-DD) of the passbook event. */
  date: string;
  /** Cumulative EPF contributions (employee + employer) to date, in ₹. */
  cumContribution: number;
  /** Cumulative EPF interest (employee + employer) to date, in ₹. */
  cumInterest: number;
  /** Total EPF value = cumContribution + cumInterest, in ₹. */
  value: number;
};

export const EPF_HISTORY: EpfHistoryPoint[] = [
  { date: "2019-02-01", cumContribution: 2053, cumInterest: 0, value: 2053 },
  { date: "2019-03-01", cumContribution: 4247, cumInterest: 0, value: 4247 },
  { date: "2019-03-31", cumContribution: 4247, cumInterest: 14, value: 4261 },
  { date: "2019-04-01", cumContribution: 6441, cumInterest: 14, value: 6455 },
  { date: "2019-05-01", cumContribution: 8635, cumInterest: 14, value: 8649 },
  { date: "2019-06-01", cumContribution: 10829, cumInterest: 14, value: 10843 },
  { date: "2019-07-01", cumContribution: 13023, cumInterest: 14, value: 13037 },
  { date: "2019-08-01", cumContribution: 15217, cumInterest: 14, value: 15231 },
  { date: "2019-09-01", cumContribution: 17568, cumInterest: 14, value: 17582 },
  { date: "2019-10-01", cumContribution: 19919, cumInterest: 14, value: 19933 },
  { date: "2019-11-01", cumContribution: 22270, cumInterest: 14, value: 22284 },
  { date: "2019-12-01", cumContribution: 24621, cumInterest: 14, value: 24635 },
  { date: "2020-01-01", cumContribution: 26972, cumInterest: 14, value: 26986 },
  { date: "2020-02-01", cumContribution: 29323, cumInterest: 14, value: 29337 },
  { date: "2020-03-01", cumContribution: 31674, cumInterest: 14, value: 31688 },
  { date: "2020-03-31", cumContribution: 31674, cumInterest: 1426, value: 33100 },
  { date: "2020-04-01", cumContribution: 34025, cumInterest: 1426, value: 35451 },
  { date: "2020-05-01", cumContribution: 36376, cumInterest: 1426, value: 37802 },
  { date: "2020-06-01", cumContribution: 38127, cumInterest: 1426, value: 39553 },
  { date: "2020-07-01", cumContribution: 40477, cumInterest: 1426, value: 41903 },
  { date: "2020-08-01", cumContribution: 42827, cumInterest: 1426, value: 44253 },
  { date: "2020-09-01", cumContribution: 45177, cumInterest: 1426, value: 46603 },
  { date: "2020-10-01", cumContribution: 47527, cumInterest: 1426, value: 48953 },
  { date: "2020-11-01", cumContribution: 49877, cumInterest: 1426, value: 51303 },
  { date: "2020-12-01", cumContribution: 49877, cumInterest: 1426, value: 51303 },
  { date: "2021-01-01", cumContribution: 49877, cumInterest: 1426, value: 51303 },
  { date: "2021-02-01", cumContribution: 60715, cumInterest: 1426, value: 62141 },
  { date: "2021-03-01", cumContribution: 77515, cumInterest: 1426, value: 78941 },
  { date: "2021-03-31", cumContribution: 77515, cumInterest: 5277, value: 82792 },
  { date: "2021-04-01", cumContribution: 94315, cumInterest: 5277, value: 99592 },
  { date: "2021-05-01", cumContribution: 110845, cumInterest: 5277, value: 116122 },
  { date: "2021-06-01", cumContribution: 127645, cumInterest: 5277, value: 132922 },
  { date: "2021-07-01", cumContribution: 144445, cumInterest: 5277, value: 149722 },
  { date: "2021-08-01", cumContribution: 161245, cumInterest: 5277, value: 166522 },
  { date: "2021-09-01", cumContribution: 178045, cumInterest: 5277, value: 183322 },
  { date: "2021-10-01", cumContribution: 194845, cumInterest: 5277, value: 200122 },
  { date: "2021-11-01", cumContribution: 211645, cumInterest: 5277, value: 216922 },
  { date: "2021-12-01", cumContribution: 228445, cumInterest: 5277, value: 233722 },
  { date: "2022-01-01", cumContribution: 238741, cumInterest: 5277, value: 244018 },
  { date: "2022-03-31", cumContribution: 238741, cumInterest: 19297, value: 258038 },
  { date: "2022-05-01", cumContribution: 251747, cumInterest: 19297, value: 271044 },
  { date: "2022-06-01", cumContribution: 268547, cumInterest: 19297, value: 287844 },
  { date: "2022-07-01", cumContribution: 285347, cumInterest: 19297, value: 304644 },
  { date: "2022-08-01", cumContribution: 302147, cumInterest: 19297, value: 321444 },
  { date: "2022-09-01", cumContribution: 318947, cumInterest: 19297, value: 338244 },
  { date: "2022-10-01", cumContribution: 335187, cumInterest: 19297, value: 354484 },
  { date: "2022-11-01", cumContribution: 344941, cumInterest: 19297, value: 364238 },
  { date: "2022-12-01", cumContribution: 366651, cumInterest: 19297, value: 385948 },
  { date: "2023-01-01", cumContribution: 390001, cumInterest: 19297, value: 409298 },
  { date: "2023-02-01", cumContribution: 413351, cumInterest: 19297, value: 432648 },
  { date: "2023-03-01", cumContribution: 436701, cumInterest: 19297, value: 455998 },
  { date: "2023-03-31", cumContribution: 436701, cumInterest: 46369, value: 483070 },
  { date: "2023-04-01", cumContribution: 460051, cumInterest: 46369, value: 506420 },
  { date: "2023-05-01", cumContribution: 483401, cumInterest: 46369, value: 529770 },
  { date: "2023-06-01", cumContribution: 506751, cumInterest: 46369, value: 553120 },
  { date: "2023-07-01", cumContribution: 530101, cumInterest: 46369, value: 576470 },
  { date: "2023-08-01", cumContribution: 553451, cumInterest: 46369, value: 599820 },
  { date: "2023-09-01", cumContribution: 579015, cumInterest: 46369, value: 625384 },
  { date: "2023-10-01", cumContribution: 604579, cumInterest: 46369, value: 650948 },
  { date: "2023-11-01", cumContribution: 630143, cumInterest: 46369, value: 676512 },
  { date: "2023-12-01", cumContribution: 655707, cumInterest: 46369, value: 702076 },
  { date: "2024-01-01", cumContribution: 681271, cumInterest: 46369, value: 727640 },
  { date: "2024-02-01", cumContribution: 706835, cumInterest: 46369, value: 753204 },
  { date: "2024-03-01", cumContribution: 732399, cumInterest: 46369, value: 778768 },
  { date: "2024-03-31", cumContribution: 732399, cumInterest: 97136, value: 829535 },
  { date: "2024-04-01", cumContribution: 757963, cumInterest: 97136, value: 855099 },
  { date: "2024-05-01", cumContribution: 783527, cumInterest: 97136, value: 880663 },
  { date: "2024-06-01", cumContribution: 809091, cumInterest: 97136, value: 906227 },
  { date: "2024-07-01", cumContribution: 834655, cumInterest: 97136, value: 931791 },
  { date: "2024-08-01", cumContribution: 860219, cumInterest: 97136, value: 957355 },
  { date: "2024-09-01", cumContribution: 892011, cumInterest: 97136, value: 989147 },
  { date: "2024-10-01", cumContribution: 923803, cumInterest: 97136, value: 1020939 },
  { date: "2024-11-01", cumContribution: 955595, cumInterest: 97136, value: 1052731 },
  { date: "2024-12-01", cumContribution: 987387, cumInterest: 97136, value: 1084523 },
  { date: "2025-01-01", cumContribution: 1019179, cumInterest: 97136, value: 1116315 },
  { date: "2025-02-01", cumContribution: 1050971, cumInterest: 97136, value: 1148107 },
  { date: "2025-03-01", cumContribution: 1082763, cumInterest: 97136, value: 1179899 },
  { date: "2025-03-31", cumContribution: 1082763, cumInterest: 178071, value: 1260834 },
  { date: "2025-04-01", cumContribution: 1114555, cumInterest: 178071, value: 1292626 },
  { date: "2025-05-01", cumContribution: 1146347, cumInterest: 178071, value: 1324418 },
  { date: "2025-06-01", cumContribution: 1178139, cumInterest: 178071, value: 1356210 },
  { date: "2025-07-01", cumContribution: 1209931, cumInterest: 178071, value: 1388002 },
  { date: "2025-08-01", cumContribution: 1241723, cumInterest: 178071, value: 1419794 },
  { date: "2025-09-01", cumContribution: 1276655, cumInterest: 178071, value: 1454726 },
  { date: "2025-10-01", cumContribution: 1311587, cumInterest: 178071, value: 1489658 },
  { date: "2025-11-01", cumContribution: 1346519, cumInterest: 178071, value: 1524590 },
  { date: "2025-12-01", cumContribution: 1381451, cumInterest: 178071, value: 1559522 },
  { date: "2026-01-01", cumContribution: 1416383, cumInterest: 178071, value: 1594454 },
  { date: "2026-02-01", cumContribution: 1451315, cumInterest: 178071, value: 1629386 },
  { date: "2026-03-01", cumContribution: 1486247, cumInterest: 178071, value: 1664318 },
  { date: "2026-03-31", cumContribution: 1486247, cumInterest: 296970, value: 1783217 },
  { date: "2026-04-01", cumContribution: 1521179, cumInterest: 296970, value: 1818149 },
  { date: "2026-05-01", cumContribution: 1556111, cumInterest: 296970, value: 1853081 },
  { date: "2026-06-01", cumContribution: 1591043, cumInterest: 296970, value: 1888013 },
  { date: "2026-07-23", cumContribution: 1625975, cumInterest: 296970, value: 1922945 },
];

export const EPF_TOTALS = {
  contributions_inr: 1625975,
  interest_inr: 296970,
  value_inr: 1922945,
} as const;

export const EPF_HISTORY_META = {
  firstDate: "2019-02-01",
  lastDate: "2026-07-23",
  points: 95,
  source: "EPFO passbook PDFs (pension excluded)",
} as const;
